load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "booker",
    srcs = ["booker.cc"],
    hdrs = ["booker.h"],
    deps = [
        "//src/booker/proxies/resy:resy",
    ],
    visibility = ["//src:__pkg__"],
)
